name: Django CI/CD

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: SSH
      run: |
         ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@52.55.224.40

    - name: Execute custom deployment script
      run: |
        chmod +x smlive.sh
        ./smlive.sh
